apiVersion: v1
kind: Service
metadata:
  name: mediconnect-backend
spec:
  selector:
    app: mediconnect
    tier: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mediconnect-frontend
spec:
  selector:
    app: mediconnect
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
